FROM maven:3.8.4-openjdk-17-slim AS build

WORKDIR /app

COPY . .

RUN mvn clean package

# Second stage: create the final image
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/demo-1.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]